# ANL488 Project - Session-based Recommendation Systems

### Data Cleaning

In [1]:
"""
The purpose of this file to do data cleaning step of CRISP-DM for browsing, searching and product sets

"""

'\nThe purpose of this file to do data cleaning step of CRISP-DM for browsing, searching and product sets\n\n'

In [2]:
#import libraries 

import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import time 
import sys
from tqdm import tqdm

### Browsing_train

In [4]:
%%time
browsing_train = pd.read_csv('C:/Users/Lokesh/Desktop/Submission/0. Datasets/browsing_train.csv')

Wall time: 1min 2s

In [5]:
browsing_train

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885210881,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
2,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
4,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
...,...,...,...,...,...,...
36079302,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,pageview,NaN,NaN,1552162324909,38f5bd3c9a1cc5b39e6b965f1aa6c565737f58e19a560a...
36079303,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,pageview,NaN,NaN,1552162336608,38f5bd3c9a1cc5b39e6b965f1aa6c565737f58e19a560a...
36079304,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,pageview,NaN,NaN,1552162343684,38f5bd3c9a1cc5b39e6b965f1aa6c565737f58e19a560a...
36079305,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,pageview,NaN,NaN,1552162356368,433b0e71df1fe9a8d1f45647545701f6108414c40eef76...
36079306,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,pageview,NaN,NaN,1552162390080,fb12a2500433a3ef2f92eae62941ce6b2db8616ce6c992...

In [6]:
"""
the data cleaning part for browsing_train involves 
1. getting the product_events separated from the pageview (we are only interested in) this also take away the missing rows 

2. group by session id and make sure that they are in chronological order

"""

'\nthe data cleaning part for browsing_train involves \n1. getting the product_events separated from the pageview (we are only interested in) this also take away the missing rows \n\n2. group by session id and make sure that they are in chronological order\n\n'

In [7]:
browsing_train.columns

Index(['session_id_hash', 'event_type', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'hashed_url'],
      dtype='object')

In [8]:
SessionId = 'SessionId'

In [9]:
product_df = browsing_train[browsing_train['event_type'] == 'event_product']
product_df

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885210881,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
7,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885304014,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
16,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,5fa44b39fe0ecc17d713a020ebb802bbe685c6f70d059c...,1550885885435,aeb23a3bb9cb43a63d8a6a6df21dd2dc6b4862036a7558...
...,...,...,...,...,...,...
36079292,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,fbdfbd3ead2eea0b54bba77e87f920c7ffd071dd13b9ce...,1552162037373,f99dd8d9426d6e6cddaabd1d90b0a815606a44c465117d...
36079295,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162119268,a377a877cd396a3fef920104bb44b56f7a980ff4362e5d...
36079297,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162139205,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...
36079298,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162148035,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...
36079301,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,remove,886a538301450ceb8ee4eba47774c29c44cbc7ca56782d...,1552162320199,0f25eb73288ebdaf59208dced356b98e9c85078e0636c3...

In [10]:
product_df = product_df.reset_index(drop=True)
product_df

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885210881,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
2,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885304014,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
4,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,5fa44b39fe0ecc17d713a020ebb802bbe685c6f70d059c...,1550885885435,aeb23a3bb9cb43a63d8a6a6df21dd2dc6b4862036a7558...
...,...,...,...,...,...,...
10431606,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,fbdfbd3ead2eea0b54bba77e87f920c7ffd071dd13b9ce...,1552162037373,f99dd8d9426d6e6cddaabd1d90b0a815606a44c465117d...
10431607,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162119268,a377a877cd396a3fef920104bb44b56f7a980ff4362e5d...
10431608,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162139205,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...
10431609,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162148035,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...
10431610,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,remove,886a538301450ceb8ee4eba47774c29c44cbc7ca56782d...,1552162320199,0f25eb73288ebdaf59208dced356b98e9c85078e0636c3...

In [11]:
product_df[SessionId] = product_df.groupby([product_df.session_id_hash]).grouper.group_info[0]

In [12]:
product_df

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url,SessionId
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885210881,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...,419673
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...,419673
2,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...,419673
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885304014,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...,419673
4,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,5fa44b39fe0ecc17d713a020ebb802bbe685c6f70d059c...,1550885885435,aeb23a3bb9cb43a63d8a6a6df21dd2dc6b4862036a7558...,419673
...,...,...,...,...,...,...,...
10431606,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,fbdfbd3ead2eea0b54bba77e87f920c7ffd071dd13b9ce...,1552162037373,f99dd8d9426d6e6cddaabd1d90b0a815606a44c465117d...,82941
10431607,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,detail,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162119268,a377a877cd396a3fef920104bb44b56f7a980ff4362e5d...,82941
10431608,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162139205,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...,82941
10431609,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,add,c0dc796d30424b4434a0922bd7c7675c955e9821c059d1...,1552162148035,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...,82941
10431610,0676f342dc490b0f8bd9c22d16e4c67f8f7af1f85679f1...,event_product,remove,886a538301450ceb8ee4eba47774c29c44cbc7ca56782d...,1552162320199,0f25eb73288ebdaf59208dced356b98e9c85078e0636c3...,82941

In [13]:
product_df2 = product_df.sort_values(['SessionId', 'server_timestamp_epoch_ms'])

In [14]:
product_df2 = product_df2.reset_index(drop=True)
product_df2

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url,SessionId
0,00000114e1075962f022114fcfc17f2d874e694ac5d201...,event_product,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,0aa1084eddfb08e4dffbb5a2aa98a5e9679382d982dd97...,0
1,00000114e1075962f022114fcfc17f2d874e694ac5d201...,event_product,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,83b4fdad686c1be4eba335f70d23ae202b84b6153e109e...,0
2,00000114e1075962f022114fcfc17f2d874e694ac5d201...,event_product,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,33fb2d300f6bd71508a0cddd4ca78f0302f34637feeb54...,0
3,00000114e1075962f022114fcfc17f2d874e694ac5d201...,event_product,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,f6f25d612ce6a6ae447c0a40bd344e0657c84048954f28...,0
4,00000114e1075962f022114fcfc17f2d874e694ac5d201...,event_product,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,0aa1084eddfb08e4dffbb5a2aa98a5e9679382d982dd97...,0
...,...,...,...,...,...,...,...
10431606,fffffc128ba14ec4d4b2a230b4352453843b3bb59becf5...,event_product,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,369bf5eafd30de4ae1eb0c8f0a55c660266dccd85f5939...,3280583
10431607,fffffc128ba14ec4d4b2a230b4352453843b3bb59becf5...,event_product,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,53c2241664874b9e7e05515c282bc33ae6665641a985f0...,3280583
10431608,fffffc128ba14ec4d4b2a230b4352453843b3bb59becf5...,event_product,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,400a4ea44e23f4cfec9e8129d84a9cb90a0cffecbb5406...,3280583
10431609,fffffc128ba14ec4d4b2a230b4352453843b3bb59becf5...,event_product,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,0ca76955e075818c7eadaafddd0d7b565260fc83e84e06...,3280583
10431610,fffffc128ba14ec4d4b2a230b4352453843b3bb59becf5...,event_product,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,c556502992acafffde649f4fff0748f1fcce22f21f5e02...,3280583

In [15]:
product_df2.columns

Index(['session_id_hash', 'event_type', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'hashed_url', 'SessionId'],
      dtype='object')

In [16]:
product_df3 = product_df2[['SessionId', 'product_action', 'product_sku_hash', 'server_timestamp_epoch_ms']]
product_df3

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735
...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814

#### checking that sessions are in chronological order

In [17]:
def convert_timestamp(df):
    
    df['time'] = (df['server_timestamp_epoch_ms'] / 1000).astype(int)
    df['time'] = pd.to_datetime(df['time'].astype(int), unit='s')
    return df

In [18]:
convert_timestamp(product_df3)

C:\Users\Lokesh\AppData\Local\Temp/ipykernel_20008/3351975002.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time'] = (df['server_timestamp_epoch_ms'] / 1000).astype(int)
C:\Users\Lokesh\AppData\Local\Temp/ipykernel_20008/3351975002.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time'] = pd.to_datetime(df['time'].astype(int), unit='s')

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09
...,...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42

In [19]:
product_df3[product_df3['SessionId'] == 0]

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09

In [20]:
product_df3[product_df3['SessionId'] == 3280583]

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time
10431599,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550717915937,2019-02-21 02:58:35
10431600,3280583,detail,82d39b070eaa6ae74da52f5726e18207f7f79950130e01...,1550717994594,2019-02-21 02:59:54
10431601,3280583,detail,e9b83fc764d5f9c05147fd2743441c5a272b357534a84d...,1550718013565,2019-02-21 03:00:13
10431602,3280583,detail,3fcf30735f0a7db28121e2ff1724043c0595c167b76a72...,1550718048242,2019-02-21 03:00:48
10431603,3280583,detail,f7e7748e347489a20a857c4e8fc5a841feb751cf0b4373...,1550718137875,2019-02-21 03:02:17
10431604,3280583,detail,c4a8972e4179bcee1be9c2e5e327a52c263a5cfd9fa7a0...,1550718156512,2019-02-21 03:02:36
10431605,3280583,detail,29e0966c55e63d4cd53667904ce0c7e7bf71a73f203f8b...,1550718195632,2019-02-21 03:03:15
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42

In [21]:
"""
sessions do seem to be in chrological order
"""

'\nsessions do seem to be in chrological order\n'

In [22]:
#lag_features 

def lag_feature(df, group_col, target_col, offset, nan=-1):
    sr = df[target_col].shift(offset)
    sr[df[group_col] != df[group_col].shift(offset)] = nan
    return sr.fillna(nan)

In [23]:
product_df3['last_event_time'] = lag_feature(product_df3, SessionId, 'time', 1, np.nan)

C:\Users\Lokesh\AppData\Local\Temp/ipykernel_20008/3384741095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_df3['last_event_time'] = lag_feature(product_df3, SessionId, 'time', 1, np.nan)

In [24]:
product_df3

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time,last_event_time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11,NaT
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49,2019-03-12 20:43:11
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04,2019-03-12 20:59:49
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15,2019-03-12 21:38:04
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09,2019-03-12 21:39:15
...,...,...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30,2019-02-21 03:03:15
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09,2019-02-21 03:03:30
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17,2019-02-21 03:04:09
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13,2019-02-21 03:09:17
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42,2019-02-21 03:10:13

In [25]:
product_df3[product_df3['SessionId'] == 0]

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time,last_event_time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11,NaT
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49,2019-03-12 20:43:11
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04,2019-03-12 20:59:49
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15,2019-03-12 21:38:04
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09,2019-03-12 21:39:15

In [26]:
product_df3

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time,last_event_time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11,NaT
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49,2019-03-12 20:43:11
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04,2019-03-12 20:59:49
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15,2019-03-12 21:38:04
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09,2019-03-12 21:39:15
...,...,...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30,2019-02-21 03:03:15
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09,2019-02-21 03:03:30
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17,2019-02-21 03:04:09
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13,2019-02-21 03:09:17
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42,2019-02-21 03:10:13

In [28]:
new_browsing_train = product_df3
new_browsing_train

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time,last_event_time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11,NaT
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49,2019-03-12 20:43:11
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04,2019-03-12 20:59:49
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15,2019-03-12 21:38:04
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09,2019-03-12 21:39:15
...,...,...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30,2019-02-21 03:03:15
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09,2019-02-21 03:03:30
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17,2019-02-21 03:04:09
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13,2019-02-21 03:09:17
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42,2019-02-21 03:10:13

In [31]:
print(new_browsing_train.nunique())
print(new_browsing_train.isnull().sum())

SessionId                     3280584
product_action                      4
product_sku_hash                57483
server_timestamp_epoch_ms    10397354
time                          4725977
last_event_time               3929101
dtype: int64
SessionId                          0
product_action                     0
product_sku_hash                   0
server_timestamp_epoch_ms          0
time                               0
last_event_time              3280584
dtype: int64

In [32]:
browsing_train.columns

Index(['session_id_hash', 'event_type', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'hashed_url'],
      dtype='object')

In [33]:
new_browsing_train.columns

Index(['SessionId', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'time', 'last_event_time'],
      dtype='object')

In [37]:
new_browsing = new_browsing_train[['SessionId', 'product_action', 'product_sku_hash', 'server_timestamp_epoch_ms', 'time']]

In [38]:
new_browsing

,SessionId,product_action,product_sku_hash,server_timestamp_epoch_ms,time
0,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552423391039,2019-03-12 20:43:11
1,0,add,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552424389158,2019-03-12 20:59:49
2,0,detail,4945f2fa8e87cb7501702ed3dce26253296eae7a8f670f...,1552426684381,2019-03-12 21:38:04
3,0,detail,6ff8d0f30bbe66cfec7d87fc7e22bd8b1defd47ff4aaaa...,1552426755233,2019-03-12 21:39:15
4,0,detail,cf2f88cb43c1713538f7dfd2aa498a2cb9ebc0c99feeac...,1552426869735,2019-03-12 21:41:09
...,...,...,...,...,...
10431606,3280583,detail,a532a9b9d11dcb3358677f9ff2d41d95f015331acbd632...,1550718210565,2019-02-21 03:03:30
10431607,3280583,detail,3011fe75d8739f217851a68d4c7ab40cce7dd5031f9080...,1550718249795,2019-02-21 03:04:09
10431608,3280583,detail,ea950a72ea131ef7181c7dd03f1ed77396648060c1e9cd...,1550718557956,2019-02-21 03:09:17
10431609,3280583,detail,bed8a2b601108932cbd8b3b14cde1d4919262c60b35cad...,1550718613724,2019-02-21 03:10:13
10431610,3280583,detail,2b1dd7624847cfe832fb6aaba59834f34008ed2820bca3...,1550718642814,2019-02-21 03:10:42

In [39]:
print(new_browsing.nunique())
print(new_browsing.isnull().sum())

SessionId                     3280584
product_action                      4
product_sku_hash                57483
server_timestamp_epoch_ms    10397354
time                          4725977
dtype: int64
SessionId                    0
product_action               0
product_sku_hash             0
server_timestamp_epoch_ms    0
time                         0
dtype: int64

In [40]:
new_browsing.to_csv('New_browsing(product only).csv', index=False)

In [41]:
"""
for the browisng events, we have gotte the product events only and we have organise the sessions in chronological order
and check it using convert timestamp and last event functions

we export the csv filw with session id, product action, product sku, timestamp and time

"""

'\nfor the browisng events, we have gotte the product events only and we have organise the sessions in chronological order\nand check it using convert timestamp and last event functions\n\nwe export the csv filw with session id, product action, product sku, timestamp and time\n\n'

### Search events

In [42]:
%%time 

search_events = pd.read_csv('C:/Users/Lokesh/Desktop/Submission/0. Datasets/search_train.csv')

Wall time: 13.9 s

In [43]:
search_events

,session_id_hash,query_vector,clicked_skus_hash,product_skus_hash,server_timestamp_epoch_ms
0,48fade624d47870058ce07dd789ccc04e46c70c0fa2a1b...,"[-0.20255649089813232, -0.016908567398786545, ...",NaN,NaN,1548575194779
1,8731ca84ff7bb8cb647531d54e64feedb2519b4a7792a7...,"[-0.007610442116856575, -0.14909175038337708, ...",NaN,['9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af3...,1548276763869
2,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.20023074746131897, -0.03151938319206238, 0...",NaN,['7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664...,1548937997295
3,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.18556387722492218, -0.07620412111282349, 0...",NaN,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,1548938038268
4,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.03269264101982117, -0.27234694361686707, 0...",NaN,['2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef...,1548938093827
...,...,...,...,...,...
819511,9b037012702a2dadee910c6b71b691b6ba072b22f41b7b...,"[-0.04411918669939041, -0.15845978260040283, -...",['f023b48bf46355aa4844b8c9bd51e478a22f17b9be83...,['12db169815cb93aaeeb1d427d6c0eea62ba4961e43c4...,1548987598321
819512,9b037012702a2dadee910c6b71b691b6ba072b22f41b7b...,"[-0.033466748893260956, 0.06939797103404999, -...",['1379461daf84128449e010af5f2a0d37837bac53c854...,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,1548987688646
819513,fdf03b124f6cb368c42a9408bc1186e4ea1465cacd5855...,"[-0.04076826199889183, -0.3194904327392578, 0....",NaN,NaN,1548554188376
819514,fdf03b124f6cb368c42a9408bc1186e4ea1465cacd5855...,"[0.0175111535936594, -0.2686958312988281, 0.07...",NaN,['32ead81a7b89168dc472d162a3d7654db02d99bb88b3...,1548554908239
819515,fdf03b124f6cb368c42a9408bc1186e4ea1465cacd5855...,"[0.007162265479564667, -0.24418511986732483, 0...",NaN,['05ad56d73cded3e417965b566d3291dc70e8fe3070ec...,1548555018635

In [44]:
print(search_events.isnull().sum())

session_id_hash                   0
query_vector                      0
clicked_skus_hash            640021
product_skus_hash            216762
server_timestamp_epoch_ms         0
dtype: int64

In [45]:
search_events.dropna(inplace=True)

In [46]:
search_events = search_events.reset_index(drop=True)
search_events

,session_id_hash,query_vector,clicked_skus_hash,product_skus_hash,server_timestamp_epoch_ms
0,77d604ce112a107ffe3e60566778d090a0b756bcfb0a3e...,"[-0.057507239282131195, -0.12616588175296783, ...",['20e8f1c4051a6c55122bd00f25f92f91b5f125497b79...,['6c792545216e765efc2cfb6173fa17f833436116c703...,1549078957672
1,7fc129b5945b2959339da1c0675d9c9adcdbc1fc99a954...,"[-0.13372763991355896, 0.007214544340968132, 0...",['8283e8b59c283c3b72462a6f73084683524f4b0149ac...,['730383c6329e2e6d7a4cffe641414abaab78da9d1858...,1550003058242
2,3ef3f3170f85ae92b01378b2161f5e71f64caadbeefd90...,"[-0.04411918669939041, -0.15845978260040283, -...",['2901d00c55fc2e4e60ea0d0e7a48ee843491e31025af...,['12db169815cb93aaeeb1d427d6c0eea62ba4961e43c4...,1549641526668
3,3ef3f3170f85ae92b01378b2161f5e71f64caadbeefd90...,"[-0.033466748893260956, 0.06939797103404999, -...",['3983d0cd10e567317005f8f47d3592beb8aceeca2dcb...,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,1549641612879
4,8bb021a4d58b148cf577ecbe28aafa7d8a6b03caf6a637...,"[-0.033466748893260956, 0.06939797103404999, -...",['ea64b218fb45c07968ebc85129b2dfe4b22f83176c98...,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,1549083152469
...,...,...,...,...,...
179367,5f40c4052f78661cf08a005e46f76e0f94770a4a575d88...,"[-0.08861231058835983, -0.13028909265995026, -...",['2792db10256cf029d44b9db645f710d7ebcda4d72d35...,['2792db10256cf029d44b9db645f710d7ebcda4d72d35...,1549934087155
179368,8612cd65d0969951e66abe0b9ca665d479364dfc76e106...,"[-0.27505257725715637, 0.1365678906440735, 0.2...",['f467a02960c724453a934afdfcaa85a8d1831e6c5f36...,['f467a02960c724453a934afdfcaa85a8d1831e6c5f36...,1549848612198
179369,1fafcc804f39652ee4dabfd19e8365f32a44659fe0f148...,"[-0.21324104070663452, 0.03624747321009636, 0....",['5033b0bd65ef48ffa0bf8a9f3e0ac556df3577dd91c3...,['821f078019973647b7c6f9844de8edc7508981c7b7ae...,1548440154585
179370,9b037012702a2dadee910c6b71b691b6ba072b22f41b7b...,"[-0.04411918669939041, -0.15845978260040283, -...",['f023b48bf46355aa4844b8c9bd51e478a22f17b9be83...,['12db169815cb93aaeeb1d427d6c0eea62ba4961e43c4...,1548987598321
179371,9b037012702a2dadee910c6b71b691b6ba072b22f41b7b...,"[-0.033466748893260956, 0.06939797103404999, -...",['1379461daf84128449e010af5f2a0d37837bac53c854...,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,1548987688646

In [47]:
print(search_events.isnull().sum())

session_id_hash              0
query_vector                 0
clicked_skus_hash            0
product_skus_hash            0
server_timestamp_epoch_ms    0
dtype: int64

In [48]:
search_events.to_csv('search_train(clean).csv', index=False)

In [49]:
"""
For now, we just drop the missing values because there does not necesarily seem to be a need to use search events.

"""

'\nFor now, we just drop the missing values because there does not necesarily seem to be a need to use search events.\n\n'

### Product catalog

In [50]:
sku_train = pd.read_csv('C:/Users/Lokesh/Desktop/Submission/0. Datasets/sku_to_content.csv')

In [51]:
sku_train

,product_sku_hash,description_vector,category_hash,image_vector,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,NaN,NaN,NaN,NaN
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,NaN,NaN,NaN,NaN
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,"[0.27629122138023376, -0.15763211250305176, 0....",06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,"[340.3592564184389, -220.19025864725685, 154.0...",7.0
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,"[0.4058118760585785, -0.03595402091741562, 0.2...",115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,"[180.3463662921092, 222.702322343354, -8.88703...",8.0
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,"[-0.3206155300140381, 0.01991105079650879, 0.0...",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[-114.81079301576219, 84.55770104232334, 85.51...",2.0
...,...,...,...,...,...
66381,c7cc673ca3baa5fa222fffdc16379892b3a62583a48143...,NaN,NaN,NaN,NaN
66382,6641c7d2053ce48ce1e81a9653dffe56dbb79ab0704fbd...,"[-0.19150441884994507, -0.06235162168741226, -...",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[129.55668732976045, 43.27996741934932, -36.70...",3.0
66383,526a6a51717d5bb40ef2b0c47394d08c54385375633bab...,"[-0.19760936498641968, 0.4446450471878052, -0....",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[-158.25984189321855, 74.19255741438077, 199.6...",5.0
66384,21ca4ab0e2fbd3b401fbeadeb4439dcab9998fb52159ec...,NaN,NaN,NaN,NaN
66385,0eaa39fb645749da181c0637d3b420f3f103b5f6b50286...,NaN,NaN,NaN,NaN

In [52]:
sku_train.columns

Index(['product_sku_hash', 'description_vector', 'category_hash',
       'image_vector', 'price_bucket'],
      dtype='object')

In [53]:
print(sku_train.isnull().sum())

product_sku_hash          0
description_vector    34436
category_hash         34334
image_vector          38016
price_bucket          34348
dtype: int64

In [54]:
# we are going to del desription and image, it is too big too process for now
sku_df = sku_train.drop(['description_vector','image_vector'], axis=1)

In [55]:
sku_df

,product_sku_hash,category_hash,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,NaN,NaN
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,NaN,NaN
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,7.0
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,8.0
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,2.0
...,...,...,...
66381,c7cc673ca3baa5fa222fffdc16379892b3a62583a48143...,NaN,NaN
66382,6641c7d2053ce48ce1e81a9653dffe56dbb79ab0704fbd...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,3.0
66383,526a6a51717d5bb40ef2b0c47394d08c54385375633bab...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,5.0
66384,21ca4ab0e2fbd3b401fbeadeb4439dcab9998fb52159ec...,NaN,NaN
66385,0eaa39fb645749da181c0637d3b420f3f103b5f6b50286...,NaN,NaN

In [56]:
print(sku_df.isnull().sum())

product_sku_hash        0
category_hash       34334
price_bucket        34348
dtype: int64

In [58]:
#sub for missing value in category

sku_df.loc[sku_df['category_hash'].isnull(), 'category_hash'] = -1

In [59]:
print(sku_df.isnull().sum())

product_sku_hash        0
category_hash           0
price_bucket        34348
dtype: int64

In [61]:
sku_df['price_bucket'].fillna(sku_df['price_bucket'].mean(), inplace=True)

In [62]:
print(sku_df.isnull().sum())

product_sku_hash    0
category_hash       0
price_bucket        0
dtype: int64

In [63]:
sku_df

,product_sku_hash,category_hash,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,-1,5.491822
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,-1,5.491822
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,7.000000
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,8.000000
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,2.000000
...,...,...,...
66381,c7cc673ca3baa5fa222fffdc16379892b3a62583a48143...,-1,5.491822
66382,6641c7d2053ce48ce1e81a9653dffe56dbb79ab0704fbd...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,3.000000
66383,526a6a51717d5bb40ef2b0c47394d08c54385375633bab...,0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,5.000000
66384,21ca4ab0e2fbd3b401fbeadeb4439dcab9998fb52159ec...,-1,5.491822
66385,0eaa39fb645749da181c0637d3b420f3f103b5f6b50286...,-1,5.491822

In [64]:
sku_df.to_csv('New_sku.csv', index=False)